require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'

target 'digital_therapy_27481' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'GoogleSignIn', '~> 6.0.2'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true
  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'
  pod 'Braintree/DataCollector'
#  pod 'OpenSSL-Universal', '~>1.0.2.20'
  target 'digital_therapy_27481Tests' do
    inherit! :complete
    # Pods for testing
  end
  

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end

end

