# Generated by Django 2.2.24 on 2021-11-30 05:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20211129_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
