# Generated by Django 2.2.20 on 2021-09-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
