# Generated by Django 2.2.24 on 2021-11-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_item_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='category',
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_category',
            field=models.CharField(choices=[('couple', 'Couple'), ('family', 'Family'), ('friend', 'Friend'), ('self', 'Self')], default='Couple', max_length=25, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='person_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
