# Generated by Django 2.2.24 on 2021-11-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_auto_20211125_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='conversation',
            name='invited_email',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
