# Generated by Django 2.2.24 on 2021-11-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_auto_20211125_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='conversation_category',
            new_name='category',
        ),
    ]
