# Generated by Django 2.2.24 on 2021-12-16 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation', '0005_auto_20211125_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='argument',
        ),
        migrations.RemoveField(
            model_name='item',
            name='resolved',
        ),
        migrations.AddField(
            model_name='conversation',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('replied', 'Replied'), ('confirmed', 'Confirmed'), ('not_confirmed', 'Not confirmed')], default='Sent', max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='item',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listener_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
