# Generated by Django 2.2.24 on 2021-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_push_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onesignal_user_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
