# Generated by Django 2.2.24 on 2021-12-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211129_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
